### ISSUE TITLE
Console not accepting input via VNC

### ISSUE THREAD

**Issue by ghost** [RealVNC/raspi-preview#5] opened 2016-05-14 16:51 UTC
If GUI isn't started I can't type anything in the console and the only way to start GUI is to execute startx over ssh.

**Comment by sconemad** [comment] 2016-05-16 10:39
Hi @ghost251101,

Thanks very much for your feedback.

Keyboard input should work at the console. Is it possible you could tell us a bit more about your setup so we can try and understand why this isn't working for you?

Specifically:
- What version of Raspbian are you using (you can find this by doing "cat /etc/debian_version" in a terminal).
- What Raspberry Pi model are you using?
- Do you see lines containing "input: vnc-keyboard" if you run the "dmesg" command?
- Do you have a physical keyboard, mouse, or any other input device attached to the Raspberry Pi?
- If you don't mind, could you create a debug log? From the desktop, right-click on the VNC icon on the toolbar, select "Options", go to the Troubleshooting page and click "Create a debug log file", then "OK". If you then exit to command line so it goes back to the console and try entering some keystrokes.
  The debug log file is created at /var/log/vncserver-x11.log - if you email this to us at raspi@realvnc.com please, mentioning this issue.

**Comment by ghost** [comment] 2016-05-18 15:49
I reinstalled Raspbian and now it works. I was using a custom Raspbian kernel with Waveshare touch screen driver for Raspberry Pi 2 http://www.waveshare.com/wiki/7inch_HDMI_LCD_(B) and I think it was the cause. Now with original Raspbian kernel without touch screen driver it works, but of course I can't use my touch screen.

**Comment by sconemad** [comment] 2016-05-19 11:18
The Waveshare driver you link to above installs a custom kernel and corresponding /lib/modules directory, which seems to include the uinput module we use for console-mode input, which is promising. However, as far as I can tell, it doesn't install the modules.devname file required for on-demand module loading, so perhaps the issue is simply that the uinput module isn't being loaded when needed as we expect (as it is in the original Raspbian setup).

You could test this out by reinstalling the Waveshare driver and doing "sudo modprobe uinput" before launching our server. If this works, then a simple permanent fix would be to add the line "uinput" to /etc/modules to have the module load at boot time.

BTW, you should be able to do "sudo apt-get install --reinstall raspberrypi-kernel" to get back the original Raspbian kernel if you need to.

**Comment by ghost** [comment] 2016-05-20 13:31
Thanks for the solution, it works.

**Comment by Ruffio** [comment] 2016-11-15 19:03
@ghost251101 please close this issue if it has been resolved.

**Closed as completed** 2016-11-19 16:49 UTC
